// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW80BsKOjVH7HOYHZuvvtg31mrWZawSXI',
    appId: '1:317819796286:web:5a8aa4427ec1f4298a0a6f',
    messagingSenderId: '317819796286',
    projectId: 'healthcare-7e04a',
    authDomain: 'healthcare-7e04a.firebaseapp.com',
    storageBucket: 'healthcare-7e04a.appspot.com',
    measurementId: 'G-EGGXFWRZM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1vwhJWxSgnyXLv_raDVzzxnDY3_PGM7I',
    appId: '1:317819796286:android:56ce7714021e5b728a0a6f',
    messagingSenderId: '317819796286',
    projectId: 'healthcare-7e04a',
    storageBucket: 'healthcare-7e04a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK0umL_ru4MNlmpL3nYEUmu9ee0-b5vbs',
    appId: '1:317819796286:ios:e982ab8b6bc5a4db8a0a6f',
    messagingSenderId: '317819796286',
    projectId: 'healthcare-7e04a',
    storageBucket: 'healthcare-7e04a.appspot.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK0umL_ru4MNlmpL3nYEUmu9ee0-b5vbs',
    appId: '1:317819796286:ios:2031983bd730d14c8a0a6f',
    messagingSenderId: '317819796286',
    projectId: 'healthcare-7e04a',
    storageBucket: 'healthcare-7e04a.appspot.com',
    iosBundleId: 'com.example.healthcare.RunnerTests',
  );
}
